import "ITaskbarAppearanceService.idl";
import "IVersionedApi.idl";
import "ocidl.idl";

[uuid(e22e715d-1c63-4da4-a445-78695330311e)]
library ExplorerTAP
{
	[uuid(50e9ab23-97b4-4dba-8f44-5cd342f30b78)]
	coclass TaskbarAppearanceService
	{
		[default]
		interface ITaskbarAppearanceService;
		interface IVersionedApi;
	}

	[uuid(31213658-fd16-4328-b5e2-ed2903adbd2d)]
	coclass TAPSite
	{
		interface IObjectWithSite;
	};
};
