namespace TranslucentTB.Xaml.Models
{
	[bindable]
	[contentproperty("Icon")]
	runtimeclass Action : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		Action();

		String Name;
		String Description;
		Windows.UI.Xaml.Controls.IconElement Icon;
		event Windows.UI.Xaml.RoutedEventHandler Click;
	}
}
