import "Models/Primitives/AccentState.idl";

namespace TranslucentTB.Xaml.Models.Primitives
{
	unsealed runtimeclass TaskbarAppearance
	{
		TaskbarAppearance();
		TaskbarAppearance(AccentState accent, Windows.UI.Color color, Boolean showPeek, Boolean showLine);

		[noexcept]
		AccentState Accent;

		[noexcept]
		Windows.UI.Color Color;

		[noexcept]
		UInt32 BlurRadius;

		[noexcept]
		Boolean ShowPeek;

		[noexcept]
		Boolean ShowLine;
	}
}
