#pragma once

#define IDI_MAINICON                       101
#define IDI_TRAYWHITEICON                  102
#define IDI_TRAYBLACKICON                  103
#define IDR_TRAY_MENU                      104
#define ID_DESKTOP_ON_PEEK                 0x9C40
#define ID_DESKTOP_COLOR                   0x9C41
#define ID_DESKTOP_NORMAL                  0x9C42
#define ID_DESKTOP_OPAQUE                  0x9C43
#define ID_DESKTOP_CLEAR                   0x9C44
#define ID_DESKTOP_BLUR                    0x9C45
#define ID_DESKTOP_ACRYLIC                 0x9C46
#define ID_VISIBLE                         0x9C50
#define ID_VISIBLE_COLOR                   0x9C51
#define ID_VISIBLE_NORMAL                  0x9C52
#define ID_VISIBLE_OPAQUE                  0x9C53
#define ID_VISIBLE_CLEAR                   0x9C54
#define ID_VISIBLE_BLUR                    0x9C55
#define ID_VISIBLE_ACRYLIC                 0x9C56
#define ID_MAXIMISED                       0x9C60
#define ID_MAXIMISED_COLOR                 0x9C61
#define ID_MAXIMISED_NORMAL                0x9C62
#define ID_MAXIMISED_OPAQUE                0x9C63
#define ID_MAXIMISED_CLEAR                 0x9C64
#define ID_MAXIMISED_BLUR                  0x9C65
#define ID_MAXIMISED_ACRYLIC               0x9C66
#define ID_START                           0x9C70
#define ID_START_COLOR                     0x9C71
#define ID_START_NORMAL                    0x9C72
#define ID_START_OPAQUE                    0x9C73
#define ID_START_CLEAR                     0x9C74
#define ID_START_BLUR                      0x9C75
#define ID_START_ACRYLIC                   0x9C76
#define ID_CORTANA                         0x9C80
#define ID_CORTANA_COLOR                   0x9C81
#define ID_CORTANA_NORMAL                  0x9C82
#define ID_CORTANA_OPAQUE                  0x9C83
#define ID_CORTANA_CLEAR                   0x9C84
#define ID_CORTANA_BLUR                    0x9C85
#define ID_CORTANA_ACRYLIC                 0x9C86
#define ID_TIMELINE                        0x9C90
#define ID_TIMELINE_COLOR                  0x9C91
#define ID_TIMELINE_NORMAL                 0x9C92
#define ID_TIMELINE_OPAQUE                 0x9C93
#define ID_TIMELINE_CLEAR                  0x9C94
#define ID_TIMELINE_BLUR                   0x9C95
#define ID_TIMELINE_ACRYLIC                0x9C96
#define ID_PEEK_SHOW                       0x9CA0
#define ID_PEEK_DYNAMIC_MAIN_MONITOR       0x9CA1
#define ID_PEEK_DYNAMIC_ANY_MONITOR        0x9CA2
#define ID_PEEK_DYNAMIC_FOREGROUND_DESKTOP 0x9CA3
#define ID_PEEK_HIDE                       0x9CA4
#define ID_OPENLOG                         0x9CB0
#define ID_LOG                             0x9CB1
#define ID_LOG_DEBUG                       0x9CB2
#define ID_LOG_INFO                        0x9CB3
#define ID_LOG_WARN                        0x9CB4
#define ID_LOG_ERR                         0x9CB5
#define ID_LOG_OFF                         0x9CB6
#define ID_EDITSETTINGS                    0x9D00
#define ID_RETURNTODEFAULTSETTINGS         0x9D01
#define ID_DISABLESAVING                   0x9D02
#define ID_HIDETRAY                        0x9D03
#define ID_DUMPWORKER                      0x9D04
#define ID_RESETWORKER                     0x9D05
#define ID_ABOUT                           0x9D06
#define ID_EXITWITHOUTSAVING               0x9D07
#define ID_AUTOSTART                       0x9D08
#define ID_TIPS                            0x9D09
#define ID_EXIT                            0x9D0A
#define IDS_OPENLOG_NORMAL                 60001
#define IDS_OPENLOG_ERROR                  60002
#define IDS_OPENLOG_EMPTY                  60003
#define IDS_AUTOSTART_NORMAL               60004
#define IDS_AUTOSTART_DISABLED_TASKMGR     60005
#define IDS_AUTOSTART_DISABLED_GPEDIT      60006
#define IDS_AUTOSTART_ENABLED_GPEDIT       60007
#define IDS_AUTOSTART_NULL                 60008
#define IDS_AUTOSTART_ERROR                60009
#define IDS_AUTOSTART_UNKNOWN              60010
#define IDS_AUTOSTART_NO_PKG_IDENT         60011
