#pragma once

#define IDI_MAINICON                       101
#define IDI_TRAYWHITEICON                  102
#define IDI_TRAYBLACKICON                  103
#define IDR_TRAY_MENU                      104
#define ID_DESKTOP_ON_PEEK                 40001
#define ID_DESKTOP_COLOR                   40002
#define ID_DESKTOP_NORMAL                  40003
#define ID_DESKTOP_CLEAR                   40004
#define ID_DESKTOP_OPAQUE                  40005
#define ID_DESKTOP_BLUR                    40006
#define ID_DESKTOP_ACRYLIC                 40007
#define ID_VISIBLE                         40008
#define ID_VISIBLE_COLOR                   40009
#define ID_VISIBLE_NORMAL                  40010
#define ID_VISIBLE_CLEAR                   40011
#define ID_VISIBLE_OPAQUE                  40012
#define ID_VISIBLE_BLUR                    40013
#define ID_VISIBLE_ACRYLIC                 40014
#define ID_MAXIMISED                       40015
#define ID_MAXIMISED_COLOR                 40016
#define ID_MAXIMISED_NORMAL                40017
#define ID_MAXIMISED_CLEAR                 40018
#define ID_MAXIMISED_OPAQUE                40019
#define ID_MAXIMISED_BLUR                  40020
#define ID_MAXIMISED_ACRYLIC               40021
#define ID_START                           40022
#define ID_START_COLOR                     40023
#define ID_START_NORMAL                    40024
#define ID_START_CLEAR                     40025
#define ID_START_OPAQUE                    40026
#define ID_START_BLUR                      40027
#define ID_START_ACRYLIC                   40028
#define ID_CORTANA                         40029
#define ID_CORTANA_COLOR                   40030
#define ID_CORTANA_NORMAL                  40031
#define ID_CORTANA_CLEAR                   40032
#define ID_CORTANA_OPAQUE                  40033
#define ID_CORTANA_BLUR                    40034
#define ID_CORTANA_ACRYLIC                 40035
#define ID_TIMELINE                        40036
#define ID_TIMELINE_COLOR                  40037
#define ID_TIMELINE_NORMAL                 40038
#define ID_TIMELINE_CLEAR                  40039
#define ID_TIMELINE_OPAQUE                 40040
#define ID_TIMELINE_BLUR                   40041
#define ID_TIMELINE_ACRYLIC                40042
#define ID_PEEK_SHOW                       40043
#define ID_PEEK_DYNAMIC_MAIN_MONITOR       40044
#define ID_PEEK_DYNAMIC_ANY_MONITOR        40045
#define ID_PEEK_DYNAMIC_FOREGROUND_DESKTOP 40046
#define ID_PEEK_HIDE                       40047
#define ID_OPENLOG                         40048
#define ID_VERBOSE                         40049
#define ID_EDITSETTINGS                    40050
#define ID_RETURNTODEFAULTSETTINGS         40051
#define ID_DISABLESAVING                   40052
#define ID_HIDETRAY                        40053
#define ID_CLEARWINDOWCACHE                40054
#define ID_RESETWORKER                     40055
#define ID_ABOUT                           40056
#define ID_EXITWITHOUTSAVING               40057
#define ID_AUTOSTART                       40058
#define ID_TIPS                            40059
#define ID_EXIT                            40060
