namespace TranslucentTB.Xaml.Converters
{
	[default_interface]
	runtimeclass ModifyOpacitySolidColorBrushToColorValueConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		ModifyOpacitySolidColorBrushToColorValueConverter();
	}
}
