#pragma once
#include "util/strings.hpp"

#ifdef RC_INVOKED
#define APP_INFO_WIDEN(x) x
#define APP_INFO_STRINGIFY UTIL_STRINGIFY_UTF8
#else
#define APP_INFO_WIDEN UTIL_WIDEN
#define APP_INFO_STRINGIFY UTIL_STRINGIFY
#endif // RC_INVOKED

#define UTF8_APP_NAME "TranslucentTB"
#define APP_NAME APP_INFO_WIDEN(UTF8_APP_NAME)

#define APP_COPYRIGHT_YEAR_NUM 2019
#define APP_COPYRIGHT_YEAR APP_INFO_STRINGIFY(APP_COPYRIGHT_YEAR_NUM)

#define APP_VERSION_FIXED 1,0,0,1
#define APP_VERSION APP_INFO_WIDEN("1.0.0.1")
