import "Pages.FramelessPage.idl";

namespace TranslucentTB.Pages
{
	[default_interface]
	runtimeclass WelcomePage : FramelessPage
	{
		WelcomePage(String configFile);

		String ConfigFile { get; };
	}
}
