#include "dependencyproperty.h"

namespace TranslucentTB.Xaml
{
    runtimeclass BindableObjectReference : Windows.UI.Xaml.DependencyObject
    {
        BindableObjectReference();

		DECL_DEPENDENCY_PROPERTY(Object, Object);
    }
}
