import "Pages.FramelessPage.idl";

namespace TranslucentTB.Xaml.Pages
{
	[default_interface]
	runtimeclass WelcomePage : FramelessPage
	{
		WelcomePage(String configFile);

		event Windows.Foundation.EventHandler<String> DiscordJoinRequested;
	}
}
