import "Pages.FramelessPage.idl";

namespace TranslucentTB.Xaml.Pages
{
	delegate void DiscordJoinDelegate();

	[default_interface]
	runtimeclass WelcomePage : FramelessPage
	{
		WelcomePage(String configFile);

		event DiscordJoinDelegate DiscordJoinRequested;
	}
}
