#pragma once

#define IDD_COLORPICKER                 101
#define IDC_COLOR                       1001
#define IDC_COLOR2                      1002
#define IDC_R                           1003
#define IDC_G                           1004
#define IDC_B                           1005
#define IDC_RED                         1006
#define IDC_GREEN                       1007
#define IDC_BLUE                        1008
#define IDC_H                           1009
#define IDC_S                           1010
#define IDC_V                           1011
#define IDC_HUE                         1012
#define IDC_SATURATION                  1013
#define IDC_VALUE                       1014
#define IDC_NEWCOLOR                    1015
#define IDC_ALPHA                       1016
#define IDC_ALPHASLIDE                  1017
#define IDC_OLDCOLOR                    1018
#define IDC_HEXCOL                      1019
#define IDC_RSLIDER                     1020
#define IDC_GSLIDER                     1021
#define IDC_BSLIDER                     1022
#define IDC_ASLIDER                     1023
#define IDC_HSLIDER                     1024
#define IDC_SSLIDER                     1025
#define IDC_VSLIDER                     1026
#define IDC_HEXSLIDER                   1027
