parameters:
- name: platform
  default: ''
- name: configuration
  default: ''
- name: extraMsbuildArgs
  default: ''
- name: signBuild
  type: boolean
  default: false
- name: buildType
  default: ''

steps:
- checkout: self
  fetchTags: true
- powershell: $(Build.SourcesDirectory)/.azp/update-version.ps1
  displayName: Update version info
- powershell: $(Build.SourcesDirectory)/.azp/update-manifest.ps1 -BuildType ${{ parameters.buildType }}
  displayName: Update app manifest
- script: git pull
  displayName: 'Update vcpkg ports'
  workingDirectory: C:\vcpkg
- script: .\bootstrap-vcpkg.bat
  displayName: 'Bootstrap vcpkg'
  workingDirectory: C:\vcpkg
- script: vcpkg integrate install
  displayName: 'Integrate vcpkg'
- task: NuGetAuthenticate@1
  displayName: 'Authenticate NuGet'
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    restoreSolution: $(Build.SourcesDirectory)/TranslucentTB.sln
- ${{ if eq(parameters.signBuild, true) }}:
  - task: DownloadSecureFile@1
    name: acsMetadata
    displayName: 'Download Azure Code Signing metadata'
    inputs:
      secureFile: metadata.json
  - task: AzureCLI@2
    displayName: Get Azure Credentials
    inputs:
      azureSubscription: Azure Code Signing
      scriptType: pscore
      scriptLocation: inlineScript
      addSpnToEnvironment: true
      inlineScript: |
        echo "##vso[task.setvariable variable=azure_tenant_id;issecret=true]$env:tenantId"
        echo "##vso[task.setvariable variable=azure_service_principal_id;issecret=true]$env:servicePrincipalId"
        echo "##vso[task.setvariable variable=azure_federated_token;issecret=true]$env:idToken"
  - script: az login --service-principal -u "$(azure_service_principal_id)" --tenant "$(azure_tenant_id)" --allow-no-subscriptions --federated-token "$(azure_federated_token)"
    displayName: Authenticate to Azure
- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    configuration: ${{ parameters.configuration }}
    ${{ if ne(parameters.platform, '') }}:
      platform: ${{ parameters.platform }}
    solution: $(Build.SourcesDirectory)/TranslucentTB.sln
    ${{ if eq(parameters.signBuild, true) }}:
      msbuildArgs: ${{ parameters.extraMsbuildArgs }} /p:CertificateTimestampServer="http://timestamp.acs.microsoft.com" /p:AcsMetadata="$(acsMetadata.secureFilePath)" /p:SignToolDigestAlgorithm=sha256 /p:BuildType=${{ parameters.buildType }}
    ${{ else }}:
      msbuildArgs: ${{ parameters.extraMsbuildArgs }} /p:BuildType=${{ parameters.buildType }}
- ${{ if eq(parameters.signBuild, true) }}:
  - script: az account clear
    displayName: Logout from Azure
    condition: always()
- task: VSTest@2
  displayName: 'Run unit tests'
  condition: and(succeededOrFailed(), ne(${{ parameters.platform }}, 'ARM64'))
  inputs:
    testAssemblyVer2: x64\$(configuration)\Tests.exe
    runInParallel: true
    platform: x64
    configuration: $(configuration)
    testRunTitle: 'x64 $(configuration)'
