set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

include("${CMAKE_CURRENT_LIST_DIR}/base.cmake")

set(VCPKG_C_FLAGS ${BASE_C_FLAGS})
set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS} ${BASE_CXX_FLAGS}")

set(VCPKG_LINKER_FLAGS ${BASE_LINKER_FLAGS})

