namespace TranslucentTB.Xaml.Controls
{
	[default_interface]
	[contentproperty("Icon")]
	runtimeclass ChromeButton : Windows.UI.Xaml.Controls.Primitives.ToggleButton
	{
		ChromeButton();

		Windows.UI.Xaml.Controls.IconElement Icon;
		static Windows.UI.Xaml.DependencyProperty IconProperty { get; };

		Windows.UI.Color NormalForeground;
		static Windows.UI.Xaml.DependencyProperty NormalForegroundProperty { get; };

		Windows.UI.Color NormalBackground;
		static Windows.UI.Xaml.DependencyProperty NormalBackgroundProperty { get; };

		Windows.UI.Color HoverForeground;
		static Windows.UI.Xaml.DependencyProperty HoverForegroundProperty { get; };

		Windows.UI.Color HoverBackground;
		static Windows.UI.Xaml.DependencyProperty HoverBackgroundProperty { get; };

		Windows.UI.Color PressedForeground;
		static Windows.UI.Xaml.DependencyProperty PressedForegroundProperty { get; };

		Windows.UI.Color PressedBackground;
		static Windows.UI.Xaml.DependencyProperty PressedBackgroundProperty { get; };

		Boolean IsTogglable;
		static Windows.UI.Xaml.DependencyProperty IsTogglableProperty { get; };
	}
}
