import "Models/Primitives/TaskbarState.idl";
import "Pages/FramelessPage.idl";

namespace TranslucentTB.Xaml.Pages
{
	delegate void ColorChangedDelegate(Windows.UI.Color previewColor);
	delegate void ChangesCommittedDelegate(Windows.UI.Color newColor);

	runtimeclass ColorPickerPage : FramelessPage
	{
		ColorPickerPage(TranslucentTB.Xaml.Models.Primitives.TaskbarState state, Windows.UI.Color originalColor);
		event ColorChangedDelegate ColorChanged;
		event ChangesCommittedDelegate ChangesCommitted;

		[noexcept]
		Windows.UI.Color OriginalColor { get; };
	}
}
