import "Pages/FramelessPage.idl";

namespace TranslucentTB.Xaml.Pages
{
	delegate void ChangesCommittedDelegate(Windows.UI.Color newColor);

	runtimeclass ColorPickerPage : FramelessPage
	{
		ColorPickerPage(String category, Windows.UI.Color currentColor);
		event ChangesCommittedDelegate ChangesCommitted;
	}
}
