namespace TranslucentTB.Xaml.Pages
{
	delegate void ClosedDelegate();

	[default_interface]
	[contentproperty("UserContent")]
	unsealed runtimeclass FramelessPage : Windows.UI.Xaml.Controls.Page
	{
		FramelessPage();

		overridable Boolean RequestClose();

		protected void Close();
		event ClosedDelegate Closed;

		String Title;
		static Windows.UI.Xaml.DependencyProperty TitleProperty { get; };

		Windows.UI.Xaml.UIElement UserContent;
		static Windows.UI.Xaml.DependencyProperty UserContentProperty { get; };

		Boolean IsClosable;
		static Windows.UI.Xaml.DependencyProperty IsClosableProperty { get; };
	}
}
