import "Pages/FramelessPage.idl";

namespace TranslucentTB.Xaml.Pages
{
	unsealed runtimeclass FramelessPageWithMessageDialog : FramelessPage
	{
		[method_name("Create")]
		protected FramelessPageWithMessageDialog(String content);

		[method_name("CreateWithTitle")]
		protected FramelessPageWithMessageDialog(String content, String title);

		protected Windows.UI.Popups.MessageDialog Dialog { get; };
	}
}
