import "Models/Primitives/LogLevel.idl";
import "Models/Primitives/LogSinkState.idl";
import "Models/Primitives/TaskbarAppearance.idl";
import "Models/Primitives/TaskbarState.idl";

namespace TranslucentTB.Xaml.Pages
{
	delegate void TaskbarSettingsChangedDelegate(TranslucentTB.Xaml.Models.Primitives.TaskbarState state, TranslucentTB.Xaml.Models.Primitives.TaskbarAppearance appearance);
	delegate void ColorRequestedDelegate(TranslucentTB.Xaml.Models.Primitives.TaskbarState state);

	delegate void OpenLogFileRequestedDelegate();
	delegate void LogLevelChangedDelegate(TranslucentTB.Xaml.Models.Primitives.LogLevel level);
	delegate void DumpDynamicStateRequestedDelegate();
	delegate void EditSettingsRequestedDelegate();
	delegate void ResetSettingsRequestedDelegate();
	delegate void DisableSavingSettingsChangedDelegate(Boolean disabled);
	delegate void HideTrayRequestedDelegate();
	delegate void ResetDynamicStateRequestedDelegate();
	delegate void CompactThunkHeapRequestedDelegate();

	delegate void StartupStateChangedDelegate();
	delegate void TipsAndTricksRequestedDelegate();
	delegate void AboutRequestedDelegate();
	delegate void ExitRequestedDelegate();

	runtimeclass TrayFlyoutPage : Windows.UI.Xaml.Controls.Page, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		TrayFlyoutPage(Boolean hasPackageIdentity);

		event TaskbarSettingsChangedDelegate TaskbarSettingsChanged;
		event ColorRequestedDelegate ColorRequested;

		event OpenLogFileRequestedDelegate OpenLogFileRequested;
		event LogLevelChangedDelegate LogLevelChanged;
		event DumpDynamicStateRequestedDelegate DumpDynamicStateRequested;
		event EditSettingsRequestedDelegate EditSettingsRequested;
		event ResetSettingsRequestedDelegate ResetSettingsRequested;
		event DisableSavingSettingsChangedDelegate DisableSavingSettingsChanged;
		event HideTrayRequestedDelegate HideTrayRequested;
		event ResetDynamicStateRequestedDelegate ResetDynamicStateRequested;
		event CompactThunkHeapRequestedDelegate CompactThunkHeapRequested;

		event StartupStateChangedDelegate StartupStateChanged;
		event TipsAndTricksRequestedDelegate TipsAndTricksRequested;
		event AboutRequestedDelegate AboutRequested;
		event ExitRequestedDelegate ExitRequested;

		void SetTaskbarSettings(TranslucentTB.Xaml.Models.Primitives.TaskbarState state, TranslucentTB.Xaml.Models.Primitives.TaskbarAppearance appearance);
		void SetLogLevel(TranslucentTB.Xaml.Models.Primitives.LogLevel level);
		void SetDisableSavingSettings(Boolean disabled);
		void SetStartupState(Windows.Foundation.IReference<Windows.ApplicationModel.StartupTaskState> state);

		TranslucentTB.Xaml.Models.Primitives.LogSinkState SinkState;

		[noexcept]
		Boolean IsBlurSupported { get; };

		[noexcept]
		Boolean HasPackageIdentity { get; };
	}
}
